name: faiedapplauncher
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.3
  math_expressions: ^2.0.1
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  http: ^1.2.1
  geolocator: ^12.0.0
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^17.1.2
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
